FirebaseError: Firebase: Error (auth/missing-password).     at createErrorInternal (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/d9ef2_@firebase_auth_dist_esm2017_5215f8b7._.js:542:41)     at _fail (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/d9ef2_@firebase_auth_dist_esm2017_5215f8b7._.js:507:11)     at _performFetchWithErrorHandling (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/d9ef2_@firebase_auth_dist_esm2017_5215f8b7._.js:968:17)     at async _performSignInRequest (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/d9ef2_@firebase_auth_dist_esm2017_5215f8b7._.js:984:28)     at async createUserWithEmailAndPassword (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/d9ef2_@firebase_auth_dist_esm2017_5215f8b7._.js:5889:22)     at async AppDataProvider.useCallback[addUser] (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/src_2bcf6cb1._.js:600:40)     at async handleAddUserSubmit (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/src_7b6b626d._.js:1632:13)     at async handleSubmit (https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/src_7b6b626d._.js:923:9)     at async https://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/static/chunks/node_modules_02c02753._.js:6758:21