A form field element should have an id or name attribute A form field element has neither an id nor a name attribute. This might prevent the browser from correctly autofilling the form.
To fix this issue, add a unique id or name attribute to a form field. This is not strictly needed, but still recommended even if you have an autocomplete attribute on the same element.

An element doesn't have an autocomplete attribute
A form field has an id or name attribute that the browser's autofill recognizes. However, it doesn't have an autocomplete attribute assigned. This might prevent the browser from correctly autofilling the form.

To fix this issue, provide an autocomplete attribute.

2 recursos

UserForm handleSubmit data (raw from RHF): {
  "username": "teste",
  "email": "naoconseguenedc@gmail.com",
  "role": "user",
  "password": "123456",
  "confirmPassword": "123456"
}
AppDataContext.tsx:316 AppDataContext addUser received userData.password: undefined
AppDataContext.tsx:328

            POST https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyD3Izvy3_vS0BqK8itmaitNOgFyndcVkp4 400 (Bad Request)
(anônimo) @ index.ts:189
await in (anônimo)
_performFetchWithErrorHandling @ index.ts:206
_performApiRequest @ index.ts:146
_performSignInRequest @ index.ts:264
signUp @ sign_up.ts:49
handleRecaptchaFlow @ recaptcha_enterprise_verifier.ts:262
createUserWithEmailAndPassword @ email_and_password.ts:295
AppDataProvider.useCallback[addUser] @ AppDataContext.tsx:328
handleAddUserSubmit @ page.tsx:48
handleSubmit @ UserForm.tsx:136
(anônimo) @ createFormControl.ts:1195
await in (anônimo)
executeDispatch @ react-dom-client.development.js:16426
runWithFiberInDEV @ react-dom-client.development.js:1510
processDispatchQueue @ react-dom-client.development.js:16476
(anônimo) @ react-dom-client.development.js:17074
batchedUpdates$1 @ react-dom-client.development.js:3253
dispatchEventForPluginEventSystem @ react-dom-client.development.js:16630
dispatchEvent @ react-dom-client.development.js:20716
dispatchDiscreteEvent @ react-dom-client.development.js:20684
AppDataContext.tsx:339  Error adding user to Firebase Auth or Firestore: FirebaseError: Firebase: Error (auth/missing-password).
    at createErrorInternal (assert.ts:146:55)
    at _fail (assert.ts:65:9)
    at _performFetchWithErrorHandling (index.ts:243:9)
    at async _performSignInRequest (index.ts:264:26)
    at async createUserWithEmailAndPassword (email_and_password.ts:302:20)
    at async AppDataProvider.useCallback[addUser] (AppDataContext.tsx:328:30)
    at async handleAddUserSubmit (page.tsx:48:7)
    at async handleSubmit (UserForm.tsx:136:7)
    at async createFormControl.ts:1195:11
error @ intercept-console-error.ts:41
AppDataProvider.useCallback[addUser] @ AppDataContext.tsx:339
await in AppDataProvider.useCallback[addUser]
handleAddUserSubmit @ page.tsx:48
handleSubmit @ UserForm.tsx:136
(anônimo) @ createFormControl.ts:1195
await in (anônimo)
executeDispatch @ react-dom-client.development.js:16426
runWithFiberInDEV @ react-dom-client.development.js:1510
processDispatchQueue @ react-dom-client.development.js:16476
(anônimo) @ react-dom-client.development.js:17074
batchedUpdates$1 @ react-dom-client.development.js:3253
dispatchEventForPluginEventSystem @ react-dom-client.development.js:16630
dispatchEvent @ react-dom-client.development.js:20716
dispatchDiscreteEvent @ react-dom-client.development.js:20684
use-websocket.ts:16  WebSocket connection to 'wss://6000-firebase-studio-1747491490302.cluster-duylic2g3fbzerqpzxxbw6helm.cloudworkstations.dev/_next/webpack-hmr' failed: